version: "3"
services:
  jupython:
    build: .
    image: jupython/machine_learning
    command: /bin/bash -l -c "find  /var/app/src/ -type d -exec chmod 777 {} \; && find  /var/app/src/ -type f -exec chmod 777 \; && /opt/conda/bin/jupyter notebook --notebook-dir=/var/app --ip='*' --port=8888 --no-browser --allow-root"
    network_mode: bridge
    container_name: juPyter
    volumes:
      - ./src:/var/app/src
      - ./data:/var/app/data
    ports:
      - 8888:8888
